
# Avaliação Prática — Fundamentos de Pandas (Módulo 3)

Esta avaliação contém **10 questões** de nível introdutório sobre **Pandas** e **análise de dados**.
O foco é demonstrar domínio das operações básicas de **importação**, **inspeção** e **manipulação simples** de DataFrames.

**Instruções gerais:**
- Responda **apenas** nas células de código logo abaixo de cada enunciado.
- Execute a célula **Setup** antes de começar.
- Utilize o arquivo CSV fornecido: **`avaliacao_empresa.csv`** (na mesma pasta deste notebook).

In [3]:

# Setup (execute esta célula primeiro — não alterar)
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt

pd.set_option("display.max_rows", 30)
pd.set_option("display.max_columns", 30)
print("Ambiente pronto.")

Ambiente pronto.

### Questão 1) Importe o arquivo CSV e crie um DataFrame chamado `df`.

In [4]:
# Insira o código que importa o .csv e o transforma em DataFrame (há um método que faz as duas coisas)
# Dica: use pd.read_csv(...)
# CAMINHO = "avaliacao_empresa.csv"
# df = ...

df = pd.read_csv("avaliacao_empresa.csv")

### Questão 2) Mostre os **5 primeiros** elementos do DataFrame.

In [5]:
# Escreva o comando para visualizar as 5 primeiras linhas do DataFrame
# ...
df.head()

,id_funcionario,nome,departamento,turno,cidade,data,vendas_qtd,ticket_medio,faturamento,custo,lucro,horas_trabalhadas,salario
0,2,Bruno,Operacoes,Tarde,Campinas,2025-01-01,56,975.0,54600.0,41435.15,13164.85,166,8086
1,3,Carla,TI,Noite,Sao Paulo,2025-01-08,50,415.0,20750.0,10791.38,9958.62,142,8703
2,4,Diego,Vendas,Manha,Campinas,2025-01-15,55,107.0,5885.0,4287.17,1597.83,130,8221
3,5,Elaine,Operacoes,Tarde,Sao Paulo,2025-01-22,11,755.0,8305.0,4328.67,3976.33,147,4954
4,6,Fabio,TI,Noite,Campinas,2025-01-29,44,456.0,20064.0,11597.60,8466.40,158,6378

### Questão 3) Exiba as **informações gerais** do DataFrame (tipos de dados e nulos).

In [6]:
# Use o método apropriado para ver tipos de dados e contagem de nulos
# ...
df.info

<bound method DataFrame.info of     id_funcionario      nome departamento  turno     cidade        data  \
0                2     Bruno    Operacoes  Tarde   Campinas  2025-01-01
1                3     Carla           TI  Noite  Sao Paulo  2025-01-08
2                4     Diego       Vendas  Manha   Campinas  2025-01-15
3                5    Elaine    Operacoes  Tarde  Sao Paulo  2025-01-22
4                6     Fabio           TI  Noite   Campinas  2025-01-29
5                7   Giovana       Vendas  Manha  Sao Paulo  2025-02-05
6                8  Henrique    Operacoes  Tarde   Campinas  2025-02-12
7                9      Iris           TI  Noite  Sao Paulo  2025-02-19
8               10      Joao       Vendas  Manha   Campinas  2025-02-26
9               11     Karen    Operacoes  Tarde  Sao Paulo  2025-03-05
10              12     Lucas           TI  Noite   Campinas  2025-03-12
11              13    Marina       Vendas  Manha  Sao Paulo  2025-03-19
12              14   Nicolas    Operacoes  Tarde   Campinas  2025-03-26
13              15    Olivia           TI  Noite  Sao Paulo  2025-04-02
14              16     Paulo       Vendas  Manha   Campinas  2025-04-09
15              17    Queila    Operacoes  Tarde  Sao Paulo  2025-04-16
16              18      Rafa           TI  Noite   Campinas  2025-04-23
17              19      Sara       Vendas  Manha  Sao Paulo  2025-04-30
18              20       Teo    Operacoes  Tarde   Campinas  2025-05-07
19               1       Ana           TI  Noite  Sao Paulo  2025-05-14
20               2     Bruno       Vendas  Manha   Campinas  2025-05-21
21               3     Carla    Operacoes  Tarde  Sao Paulo  2025-05-28
22               4     Diego           TI  Noite   Campinas  2025-06-04
23               5    Elaine       Vendas  Manha  Sao Paulo  2025-06-11
24               6     Fabio    Operacoes  Tarde   Campinas  2025-06-18
25               7   Giovana           TI  Noite  Sao Paulo  2025-06-25

    vendas_qtd  ticket_medio  faturamento     custo     lucro  \
0           56         975.0      54600.0  41435.15  13164.85
1           50         415.0      20750.0  10791.38   9958.62
2           55         107.0       5885.0   4287.17   1597.83
3           11         755.0       8305.0   4328.67   3976.33
4           44         456.0      20064.0  11597.60   8466.40
5           37         874.0      32338.0  25812.20   6525.80
6           43         971.0      41753.0  33218.02   8534.98
7           51         324.0      16524.0  10658.24   5865.76
8           29         149.0       4321.0   2618.33   1702.67
9           49        1384.0      67816.0  44195.04  23620.96
10          19         795.0      15105.0   7537.49   7567.51
11          10         369.0       3690.0   2497.44   1192.56
12          44         617.0      27148.0  10899.75  16248.25
13          41         316.0      12956.0   6569.21   6386.79
14          15         813.0      12195.0   9010.40   3184.60
15           7        1138.0       7966.0   3477.94   4488.06
16          44         810.0      35640.0  26677.81   8962.19
17          40         937.0      37480.0  15880.30  21599.70
18          37         552.0      20424.0   9396.67  11027.33
19          27         631.0      17037.0  13484.77   3552.23
20          29         947.0      27463.0  17993.72   9469.28
21          57         311.0      17727.0  10212.97   7514.03
22           7         663.0       4641.0   2035.92   2605.08
23          57         401.0      22857.0  15284.61   7572.39
24          32        1323.0      42336.0  28148.61  14187.39
25          51        1283.0      65433.0  50905.52  14527.48

    horas_trabalhadas  salario
0                 166     8086
1                 142     8703
2                 130     8221
3                 147     4954
4                 158     6378
5                 184     8193
6                 157     4556
7                 129     3476
8                 197     6137
9                 155     6438
10                199     3274
11                190     4463
12                169     8429
13                197     8746
14                176     7230
15                139     6609
16                174     5475
17                172     5642
18                150     8342
19                151     6916
20                163     7461
21                148     4709
22                152     9297
23                121     5092
24                162     4029
25                168     8894  >

### Questão 4) Mostre o **formato (linhas, colunas)** e a **lista de colunas** do DataFrame.

In [7]:
# Mostre df.shape e df.columns
# ...
df.shape
df.columns

Index(['id_funcionario', 'nome', 'departamento', 'turno', 'cidade', 'data',
       'vendas_qtd', 'ticket_medio', 'faturamento', 'custo', 'lucro',
       'horas_trabalhadas', 'salario'],
      dtype='str')

### Questão 5) Exiba as **estatísticas descritivas** das colunas numéricas (média, min, max, etc.).

In [8]:
# Utilize o método para estatísticas descritivas
# ...
df.describe

<bound method NDFrame.describe of     id_funcionario      nome departamento  turno     cidade        data  \
0                2     Bruno    Operacoes  Tarde   Campinas  2025-01-01
1                3     Carla           TI  Noite  Sao Paulo  2025-01-08
2                4     Diego       Vendas  Manha   Campinas  2025-01-15
3                5    Elaine    Operacoes  Tarde  Sao Paulo  2025-01-22
4                6     Fabio           TI  Noite   Campinas  2025-01-29
5                7   Giovana       Vendas  Manha  Sao Paulo  2025-02-05
6                8  Henrique    Operacoes  Tarde   Campinas  2025-02-12
7                9      Iris           TI  Noite  Sao Paulo  2025-02-19
8               10      Joao       Vendas  Manha   Campinas  2025-02-26
9               11     Karen    Operacoes  Tarde  Sao Paulo  2025-03-05
10              12     Lucas           TI  Noite   Campinas  2025-03-12
11              13    Marina       Vendas  Manha  Sao Paulo  2025-03-19
12              14   Nicolas    Operacoes  Tarde   Campinas  2025-03-26
13              15    Olivia           TI  Noite  Sao Paulo  2025-04-02
14              16     Paulo       Vendas  Manha   Campinas  2025-04-09
15              17    Queila    Operacoes  Tarde  Sao Paulo  2025-04-16
16              18      Rafa           TI  Noite   Campinas  2025-04-23
17              19      Sara       Vendas  Manha  Sao Paulo  2025-04-30
18              20       Teo    Operacoes  Tarde   Campinas  2025-05-07
19               1       Ana           TI  Noite  Sao Paulo  2025-05-14
20               2     Bruno       Vendas  Manha   Campinas  2025-05-21
21               3     Carla    Operacoes  Tarde  Sao Paulo  2025-05-28
22               4     Diego           TI  Noite   Campinas  2025-06-04
23               5    Elaine       Vendas  Manha  Sao Paulo  2025-06-11
24               6     Fabio    Operacoes  Tarde   Campinas  2025-06-18
25               7   Giovana           TI  Noite  Sao Paulo  2025-06-25

    vendas_qtd  ticket_medio  faturamento     custo     lucro  \
0           56         975.0      54600.0  41435.15  13164.85
1           50         415.0      20750.0  10791.38   9958.62
2           55         107.0       5885.0   4287.17   1597.83
3           11         755.0       8305.0   4328.67   3976.33
4           44         456.0      20064.0  11597.60   8466.40
5           37         874.0      32338.0  25812.20   6525.80
6           43         971.0      41753.0  33218.02   8534.98
7           51         324.0      16524.0  10658.24   5865.76
8           29         149.0       4321.0   2618.33   1702.67
9           49        1384.0      67816.0  44195.04  23620.96
10          19         795.0      15105.0   7537.49   7567.51
11          10         369.0       3690.0   2497.44   1192.56
12          44         617.0      27148.0  10899.75  16248.25
13          41         316.0      12956.0   6569.21   6386.79
14          15         813.0      12195.0   9010.40   3184.60
15           7        1138.0       7966.0   3477.94   4488.06
16          44         810.0      35640.0  26677.81   8962.19
17          40         937.0      37480.0  15880.30  21599.70
18          37         552.0      20424.0   9396.67  11027.33
19          27         631.0      17037.0  13484.77   3552.23
20          29         947.0      27463.0  17993.72   9469.28
21          57         311.0      17727.0  10212.97   7514.03
22           7         663.0       4641.0   2035.92   2605.08
23          57         401.0      22857.0  15284.61   7572.39
24          32        1323.0      42336.0  28148.61  14187.39
25          51        1283.0      65433.0  50905.52  14527.48

    horas_trabalhadas  salario
0                 166     8086
1                 142     8703
2                 130     8221
3                 147     4954
4                 158     6378
5                 184     8193
6                 157     4556
7                 129     3476
8                 197     6137
9                 155     6438
10                199     3274
11                190     4463
12                169     8429
13                197     8746
14                176     7230
15                139     6609
16                174     5475
17                172     5642
18                150     8342
19                151     6916
20                163     7461
21                148     4709
22                152     9297
23                121     5092
24                162     4029
25                168     8894  >

### Questão 6) Selecione apenas as colunas `nome` e `departamento` e mostre as **5 primeiras** linhas.

In [9]:
# Selecione as colunas solicitadas e mostre 5 primeiras linhas
# ...
df[['nome', 'departamento']].head()

     nome departamento
0   Bruno    Operacoes
1   Carla           TI
2   Diego       Vendas
3  Elaine    Operacoes
4   Fabio           TI

### Questão 7) Filtre os registros do **turno 'Noite'** e **conte** quantos registros existem.

In [10]:
# Filtre df['turno'] == 'Noite' e conte as linhas resultantes
# ...
len(df[df['turno'] == 'Noite'])

9

### Questão 8) O código abaixo converte as datas de texto para data e em seguida cria uma coluna mês para os dados.
Mostre as **5 primeiras** linhas de `df[['data','mes']]`.

In [11]:
df['data']=pd.to_datetime(df['data'],errors='coerce')
df['mes']=df['data'].dt.to_period('M').astype(str)
df[['data','mes']]
#Insira o seu código aqui
df[['data', 'mes']].head()

        data      mes
0 2025-01-01  2025-01
1 2025-01-08  2025-01
2 2025-01-15  2025-01
3 2025-01-22  2025-01
4 2025-01-29  2025-01

### Questão 9) O código abaixo agrupa e soma os valores por mes no DataFrame fat.
Mostre os **3 meses** com maior faturamento.

In [12]:
fat = df.groupby('mes',as_index=False)['faturamento'].sum()
fat.sort_values('faturamento', ascending=False).head(3)

       mes  faturamento
5  2025-06     135267.0
2  2025-03     113759.0
0  2025-01     109604.0

### Questão 10) Calcule a **média de salário por departamento** e mostre em **ordem decrescente**.

In [13]:
#df.groupby('departamento',as_index=False)['salario'].mean().sort_values('salario',ascending=False)
salarios_por_departamento = df.groupby('departamento',as_index=False)['salario'].mean().sort_values('salario', ascending=False)
#Insira seu código aqui


---
## Extra (não avaliativo) — Demonstração de visualização

O gráfico abaixo mostra a **distribuição do faturamento por mês e por departamento** (barras empilhadas).  
**Ação do aluno:** **apenas execute** a célula para observar o resultado e refletir sobre variações por mês e por área.

In [ ]:

# ▶️ Execute esta célula (não alterar o código)
# Pré-requisitos: df já carregado; coluna 'data' convertida; coluna 'mes' criada (Questões 1 e 8).
df['data'] = pd.to_datetime(df['data'], errors='coerce')
df['mes'] = df['data'].dt.to_period('M').astype(str)

fat_mes_dep = df.groupby(['mes','departamento'], as_index=False)['faturamento'].sum()
pivot = fat_mes_dep.pivot(index='mes', columns='departamento', values='faturamento').fillna(0)

ax = pivot.plot(kind='bar', stacked=True, figsize=(10,6))
ax.set_title("Faturamento por Mês e Departamento (barras empilhadas)")
ax.set_xlabel("Mês (YYYY-MM)")
ax.set_ylabel("Faturamento (R$)")
import matplotlib.pyplot as plt
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()